@startuml

class Detective {
    + Detective(cronometro, ciudad, contadorDeDificultad)
    + visitar(nombreEdificio): Pista
    + viajar(ciudad: Ciudad)
    + recibirHeridaDeCuchillo()
    + dormir()
}

class Cronometro {
    + restar(horas: int)
    + tiempo(): int
}

Detective "1" -> "1" Cronometro


@enduml
