@startuml

class Ladron

interface ObjetoRobado

class Comunes implements ObjetoRobado
class Valiosos implements ObjetoRobado
class MuyValiosos implements ObjetoRobado

Ladron "1" --> "1" ObjetoRobado

@enduml
