@startuml

class Escenario {
    - policia: Policia
    - ladron: Ladron
    - ciudades: Ciudad[*]
    - nombreEnOrdenDeArresto
    + Escenario(policia, ladron, ciudades)
    + policiaVisitar(nombreEdificio): Pista
    + policiaViajar(nombreCiudad)
    + policiaRecibirHeridaDeCuchillo()
    + policiaRecibirHeridaPorArmaDeFuego()
    + policiaDormir()
    + policiaAtraparLadron(): boolean
    + emitirOrdenDeArresto(nombre)
    + edificiosVisitables(): String[*]
    + ciudadesVisitables(): String[*]
}

@enduml
