@startuml

!include clase_algothief.plantuml
!include clase_builder.plantuml
!include clase_edificioBuilder.plantuml
!include clase_rango.plantuml
!include clase_ciudad.plantuml
!include clase_ladron.plantuml
!include clase_policia.plantuml
!include clase_escenario.plantuml

@enduml
