@startuml

class Ciudad {
    + obtenerEdificio(nombre: String): Edificio
}


class Edificio {
    + es(nombreEdificio: String) : boolean
    + obtenerPista(): Pista
}

Ciudad "1" --> "*" Edificio

abstract class Pista {
    - Descripcion: String
}

Edificio "1" --> "1" Pista

class Facil extends Pista
class Media extends Pista
class Dificil extends Pista

@enduml
