@startuml

!include ../variables.txt
!include clase_localize.plantuml
!include clase_mensaje.plantuml

title $MiVar\n

Localize <|-- Mensaje

note left of Mensaje
        Plantuml soporta inclusión de archivos y
        utilización de variables!!
        
        Esto les permite definir sus clases y
        las relaciones en archivos separados.

        Por ejemplo "MiClaseNombre" no se encuentra
        definida en este archivo.

        NOTA:
        Les recomendamos implementar esta herramienta
        para mitigar los errores de inconsistencia en los
        diagramas uml.
end note
@enduml
@startuml(id=WITHOUTNOTES)

!include ../variables.txt
!include clase_localize.plantuml!WITHOUTATTRIBUTES
!include clase_mensaje.plantuml

Localize <|-- Mensaje

@enduml
