@startuml

title "Caso de uso 4 de la entrega 1"

participant ":Testcase" as testcase
participant ":Algothief" as algothief
participant "escenario:Escenario" as escenario
participant ":Policia" as policia
participant ":Cronometro" as cronometro
participant "mexico:Ciudad" as ciudad
participant "aeropuerto:Edificio" as aeropuerto



activate testcase
loop 3 veces
    testcase -> algothief++: visitar("Aeropuerto de Mexico")
        algothief -> escenario++: policiaVisitar("Aeropuerto de Mexico")
            escenario -> policia++: visitar("Aeropuerto de Mexico")
                policia -> ciudad++: obtenerEdificio("Aeropuerto de Mexico")
                    return aeropuerto
                policia -> policia++: visitar(aeropuerto)
                    policia -> cronometro++: registrarVisita(aeropuerto)
                    alt primera visita
                        cronometro -> cronometro: restar(1)
                    else segunda visita
                        cronometro -> cronometro: restar(2)
                    else tercera visita
                        cronometro -> cronometro: restar(3)
                    end alt
                    deactivate
                    policia -> aeropuerto++: obtenerPista()
                        return pista
                    return pista
                return pista
            return pista
        deactivate algothief
end loop
testcase -> algothief++: pistaMasReciente()
    return descripcionPistaAeropuerto

loop 55 veces
    testcase -> algothief: visitar("Puerto de Mexico")
end loop
testcase -> algothief++: pistaMasReciente()
    return descripcionPistaPuerto

testcase -> algothief++: juegoAcabado()
    return true
testcase -> algothief++: juegoGanado()
    return false

testcase -> testcase++: assertEquals(descripcionEsperadaAeropuerto, descripcionPistaAeropuerto)
deactivate testcase

testcase -> testcase++: assertEquals(descripcionEsperadaPuerto, descripcionPistaPuerto)
deactivate testcase

testcase -> testcase++: assertTrue(juegoAcabado)
deactivate testcase

testcase -> testcase++: assertFalse(juegoGanado)
deactivate testcase

@enduml