@startuml

title "Caso de uso 3 de la entrega 2"

participant ":Testcase" as testcase
participant "descripcion\n:DescripcionSospechoso" as descripcion
participant ":Algothief" as algothief
participant ":DescripcionSospechoso" as descripcionAT
participant ":Ladron" as ladron
participant ":Escenario" as escenario
participant "fuente:FuenteDeDatos" as fuente
participant "hobby:Rasgo" as hobby
participant "sexo:Rasgo" as sexo

activate testcase
testcase ->> hobby**: <<create>>\nRasgo("Hobby", "Tenis")
testcase ->> sexo**: <<create>>\nRasgo("Sexo", "Femenino")
testcase ->> descripcion**: <<create>>\nDescripcionSospechoso(hobby, sexo)
testcase -> algothief++: cargarDatosSospechoso(descripcion)
    algothief -> descripcionAT++: agregar(descripcion)
        return
    return

testcase -> algothief++: buscarSospechosos()
    algothief -> fuente++: listaDeLadrones()
        return ladrones
    loop por cada ladron
        algothief -> ladron++: descripcion()
            return descripcionLadron
        algothief -> descripcionAT++: coincideCon(descripcionLadron)
            return coincide
    end loop
    algothief -> escenario: emitirOrdenDeArresto("Carmen SanDiego")
    return "Carmen SanDiego"

testcase -> testcase: assertEquals("Carmen SanDiego", "Carmen SanDiego")
activate testcase
deactivate testcase

@enduml
