@startuml

'autonumber

title "Policia visita un edificio"

participant ":Policia" as policia
participant "ciudadActual:Ciudad" as ciudad
participant ":Cronometro" as cron
participant "edificio:Edificio" as edificio

-> policia++: visitar(nombreEdificio)
policia -> ciudad++: obtenerEdificio(nombreEdificio)
    return edificio
policia -> policia++: visitar(edificio)
    policia -> cron++: registrarVisita(edificio)
        cron -> cron--: restar(tiempo)
    policia -> edificio++: obtenerPista()
        return pista
    return pista
return pista

@enduml
