@startuml

title "Caso de uso 1 de la entrega 1"

participant ":Testcase" as testcase
participant "algothief:Algothief" as algothief
participant "escenario:Escenario" as escenario
participant "cronometro\n:Cronometro" as cron
participant ":Policia" as policia
participant "ciudad: Ciudad" as ciudad
participant "banco:Edificio" as banco
participant "pista:Pista" as pista


activate testcase
testcase -> algothief++: visitar("Banco de Montreal")
    algothief -> escenario++: detectiveVisitar("Banco de Montreal")
        escenario -> policia++: visitar("Banco de Montreal")
            policia -> ciudad++: obtenerEdificio("Banco de Montreal")
                return banco
            policia -> policia++: visitar(banco)
                policia -> cron++: registrarVisita(banco)
                    cron -> cron--: restar(3)
                policia -> banco++: obtenerPista()
                    return pista
                return pista
            return pista
        return pista
    deactivate algothief

testcase -> algothief++: pistaMasReciente()
    algothief -> pista++: descripcion()
        return descripcionDeLaPista
    return descripcionDeLaPista

testcase -> testcase++: assertEquals(descripcionEsperada, descripcionDeLaPista)
deactivate testcase

@enduml
