@startuml

title "Caso de uso 3 de la entrega 2"

participant ":Testcase" as testcase
participant ":Algothief" as algothief
participant "computadora\n:Computadora" as computadora
participant ":Ladron" as ladron
participant "descripcion\n:DescripcionSospechoso" as descripcion
participant "fuente:FuenteDeDatos" as fuente
participant "hobby:Rasgo" as hobby
participant "sexo:Rasgo" as sexo

activate testcase
testcase ->> hobby**: <<create>>\nRasgo("Hobby", "Tenis")
testcase ->> sexo**: <<create>>\nRasgo("Sexo", "Femenino")
testcase ->> descripcion**: <<create>>\nDescripcionSospechoso(hobby, sexo)
testcase -> algothief: cargarDatosSospechoso(descripcion)

testcase -> algothief++: buscarSospechosos()
    algothief -> fuente++: getComputadora()
        return computadora
    algothief -> computadora++: ladronesConDescripcion(descripcion)
        loop por cada ladron
            computadora -> ladron++: descripcion()
                return descripcionLadron
            computadora -> descripcion++: coincideCon(descripcionLadron)
                return coincide
        end loop
        return ["Carmen SanDiego"]
    return ["Carmen SanDiego"]

testcase -> testcase: assertEquals(["Carmen SanDiego"], nombresDevueltos)
activate testcase
deactivate testcase

@enduml
