@startuml

title "Detective sufre herida de cuchillo"

participant ":TestCase" as testcase
participant ":Cronometro" as crono
participant "novato:Rango" as rango
participant "Montreal:Ciudad" as ciudad
participant ":Detective" as detective

testcase -> crono: new Cronometro()
    activate crono
testcase -> rango: new novato()
    activate rango
testcase -> ciudad: new ciudad("Montreal")
    activate ciudad
testcase -> detective: new detective(cronometro,Montreal, novato)
    activate detective
detective -> detective: recibirHeridaDeCuchillo()
detective -> crono: restar(2)
detective -> detective: dormir()
testcase -> testcase: assertEquals(10, cronometro.tiempo())


@enduml