@startuml

title "Caso de uso 2 de la entrega 2"

participant ":Testcase" as testcase
participant ":Algothief" as algothief
participant ":Escenario" as escenario
participant ":Policia" as policia
participant ":Cronometro" as cronometro
participant ":ContadorDeArrestos" as contador
participant "rango:Investigador" as rango
participant "fecha:LocalDateTime" as fecha
participant "montreal:Ciudad" as montreal
participant "coordenadasMontreal\n:Coordenadas" as coordenadasMontreal
participant ":Cronometro" as cron

activate testcase
testcase -> algothief++: viajar("Mexico")
    algothief -> escenario++: policiaViajar("Mexico")
        escenario -> policia++: viajar(mexico)
            policia -> contador++: rango()
                return rango
            policia -> cronometro++: registrarViaje(rango, montreal, mexico)
                cronometro -> montreal++: distanciaA(mexico)
                    montreal -> coordenadasMontreal++: distanciaA(coordenadasMexico)
                        return distancia
                    return distancia
                cronometro -> rango++: tiempoDeViaje(distancia)
                    return tiempo := distancia / 1300
                cronometro -> cronometro--: restar(tiempo)
            deactivate
        deactivate
    deactivate

testcase -> cron++: fechaActual()
    return fecha

testcase -> fecha++: getDayOfWeek()
    return diaDeLaSemana

testcase -> fecha++: getHour()
    return hora

testcase -> testcase++: assertEquals(lunes, diaDeLaSemana)
deactivate

testcase -> testcase++: assertEquals(tiempoDeViaje, hora)
deactivate


@enduml