@startuml

title "Caso de uso 1"

participant ":Testcase1" as testcase
participant "algothief:Algothief" as algothief
participant "escenario:Escenario" as escenario
participant "cronometro\n:Cronometro" as cron
participant ":Detective" as detective
participant "ciudad: Ciudad" as ciudad
participant "banco:Edificio" as banco
participant "pista:Facil" as pista


activate testcase
testcase -> algothief++: visitar("Banco Nacional")
    algothief -> escenario++: detectiveVisitar("Banco Nacional")
        escenario -> detective++: visitar("Banco Nacional")
            detective -> ciudad++: obtenerEdificio("Banco Nacional")
                return banco
            detective -> detective++: visitar(banco)
                detective -> detective: registrarVisita(banco)
                detective -> detective++: tiempoDeVisita(banco)
                    return tiempo
                detective -> cron: restar(tiempo)
                detective -> banco++: obtenerPista()
                    return pista
                return pista
            return pista
        return pista
    deactivate algothief

testcase -> algothief++: pistaMasReciente()
    algothief -> pista++: descripcion()
        return descripcionDeLaPista
    return descripcionDeLaPista

testcase -> testcase++: assertEquals("Descripción de la pista", descripcionDeLaPista)
deactivate testcase

@enduml
