@startuml

title "Caso de uso 4 de la entrega 2"

participant ":Testcase" as testcase
participant ":Algothief" as algothief

participant ":Escenario" as escenario
participant ":Ladron" as ladron


activate testcase
testcase -> algothief: atraparSospechoso()
    activate algothief
    algothief -> escenario: policiaAtraparLadron()
        activate escenario
        escenario -> ladron: seLlama(null)
            activate ladron
            return false
        return false
    deactivate algothief

testcase -> algothief: juegoAcabado()
    activate algothief
    return true

testcase -> algothief: juegoGanado()
    activate algothief
    return false

testcase -> testcase: assertTrue(juegoAcabado)
activate testcase
deactivate testcase

testcase -> testcase: assertFalse(juegoGanado)
activate testcase
deactivate testcase

@enduml
