@startuml

title "Caso de uso 2 de la entrega 2"

participant ":Testcase" as testcase
participant ":Algothief" as algothief
participant ":Cronometro" as cronometro
participant ":Escenario" as escenario
participant ":Detective" as detective
participant ":ContadorDeArrestos" as contador
participant "rango:Investigador" as rango

activate testcase
testcase -> algothief: viajar("Mexico")
    activate algothief
    algothief -> escenario: detectiveViajar("Mexico")
        activate escenario
        escenario -> detective: viajar(mexico)
            activate detective
            detective -> contador: rango()
                activate contador
                return rango
            detective -> rango: tiempoDeViaje(3800)
                activate rango
                return 3800 / 1100
            detective -> cronometro: restar(3)
            return
        return
    return

testcase -> cronometro: tiempo()
    activate cronometro
    return horas

testcase -> testcase: assertEquals(3, horas)
activate testcase
deactivate testcase

@enduml
